---
version: 5

defaults:  # Used for any hierarchy level that omits these keys.
  datadir: data         # This path is relative to hiera.yaml's directory.
  data_hash: yaml_data  # Use the built-in YAML backend.

hierarchy:
  - name: 'Per-node data'
    path: "nodes/%{trusted.certname}.yaml"

  - name: 'common'
    path: 'common.yaml'

plan_hierarchy:
  - name: 'Static data'
    path: 'common.yaml'
